server:
  port: 8989
spring:
  profiles:
    active: dev
#  datasource:
##    url: jdbc:mysql://47.98.177.86:3306/sg_blog?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
#    url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
#    username: root
#    password: 13812833598
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 2MB
#      max-request-size: 5MB
  redis:
    host: 47.98.177.86
    port: 6379
    username: default
    password: rootroot
    timeout: 0            # 连接空闲超过 N（毫秒）后关闭，0为禁用
    # 使用jedis连接池，需要排除lettuce-core，依赖jedis
    jedis:
      pool:
        max-active: 50    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 5000    # 连接池中连接用完时，新的请求等待时间(毫秒)，超过该时间抛出异常JedisConnectionException，(默认-1，负值表示没有限制，不建议使用默认值)
        max-idle: 10      # 连接池中的最大空闲连接，默认8

  #邮箱验证码配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com;163邮箱是smtp.163.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 1146713212@qq.com
    #授权码
    password: ajnjwijncehggfhh
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



mybatis-plus:
  configuration:
    # ??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto




oss:
  accessKey: "tpJ0_s96WtHEe4lihFyiE80HwFczOQ27rVEak8YA"
  secretKey: "091ttPM5jEOBMPX63fJUWoM1qQTjgYKcdPYZ8DIn"
  bucket: "yfdlblog"
  baseurl: "http://img.yfdl.site"

InitPassword: "123"  # 后台创建用户的初始密码
defaultAvatar: "http://img.yfdl.site/2022/11/05/6b4555eb80594ebf9ae16769456df68d.jpeg"
defaultNicknamePrefix: "yu_"