server:
  port: 7777
spring:
  datasource:
#    url: jdbc:mysql://47.98.177.86:3306/sg_blog?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: 13812833598
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 47.98.177.86
    port: 6379
    username: default
    password: rootroot

  #邮箱验证码配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com;163邮箱是smtp.163.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 1146713212@qq.com
    #授权码
    password: eobyeuwvoecyiebj
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: "tpJ0_s96WtHEe4lihFyiE80HwFczOQ27rVEak8YA"
  secretKey: "091ttPM5jEOBMPX63fJUWoM1qQTjgYKcdPYZ8DIn"
  bucket: "yfdlblog"
  baseurl: "http://img.yfdl.site"

InitPassword: "123"  # 后台创建用户的初始密码
defaultAvatar: "http://img.yfdl.site/2022/11/05/6b4555eb80594ebf9ae16769456df68d.jpeg"
defaultNicknamePrefix: "yu_"



